version: '3.9'

services:
  web:
    build:
      context: .
    container_name: django_gallery_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  static_volume:
  media_volume:
