version: '3.9'

services:
  web:
    build:
      context: .
    container_name: django_gallery_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: django_gallery_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gallerydb
      MYSQL_USER: galleryuser
      MYSQL_PASSWORD: gallerypass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  static_volume:
  media_volume:
  db_data:
